<MyLayout>

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 50
        spacing: 20

        Image:
            source: "../../../tensorEnv/Tkinter_prac/Projects/ImageViewer_Images/plane.png"
            # allow_stretch: True
            # keep_ratio: True

        Button:
            text: "Hello World"
            pos_hint: {'center_x': 0.5}
            size_hint: (0.3, 0.1)
